name: generate-snake

on:
  schedule:
    - cron: "0 0 * * *"  # diario
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate snake (light)
        uses: Platane/snk@v3
        with:
          github_user_name: MarcosJVPR
          outputs: |
            output/snake.svg?palette=github-light

      - name: Generate snake (dark)
        uses: Platane/snk@v3
        with:
          github_user_name: MarcosJVPR
          outputs: |
            output/snake-dark.svg?palette=github-dark

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}