name: Generate snake

on:
  schedule:
    - cron: "0 0 * * 1"   # every Monday 00:00 UTC
  workflow_dispatch:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake SVG (electric blue snake)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: MarcosJVPR
          outputs: |
            dist/snake.svg?color_snake=%23006CFF&color_dots=%23161B22,%2300BFFF,%23006CFF

      - name: Upload to GitHub Pages branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
