name: Generate snake

on:
  schedule:
    - cron: "0 0 * * 1"   # cada lunes 00:00 UTC
  workflow_dispatch:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: MarcosJVPR
          outputs: |
            # Light (azul eléctrico)
            dist/snake.svg?color_snake=006CFF&color_dots=%23161B22,%23006CFF,%2300BFFF
            # Dark (sky-blue neon)
            dist/snake-dark.svg?palette=github-dark&color_snake=7DF9FF&color_dots=%230b0f17,%237DF9FF,%2300EAFE
            # Extra light (si lo usas)
            dist/snake-light.svg?palette=github-light&color_snake=006CFF&color_dots=%23f5f9ff,%23006CFF,%2300BFFF

      - name: Upload to GitHub Pages branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
