name: Generate snake

on:
  schedule:
    - cron: "0 0 * * 1"   # cada lunes 00:00 UTC
  workflow_dispatch:
  push:
    branches: ["main"]

permissions:
  contents: write   # necesario para publicar en la rama output

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: MarcosJVPR
          outputs: |
            dist/snake.svg?color_snake=006CFF&color_dots=#161B22,#006CFF,#00BFFF
            dist/snake-dark.svg?palette=github-dark&color_snake=7DF9FF&color_dots=#0b0f17,#7DF9FF,#00EAFE
            dist/snake-light.svg?palette=github-light&color_snake=006CFF&color_dots=#f5f9ff,#006CFF,#00BFFF

      - name: Upload to GitHub Pages branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
