name: Generate snake

on:
  schedule:
    - cron: "0 0 * * 1"  # every Monday 00:00 UTC
  workflow_dispatch:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake SVG (ONLY snake + food; empty cells transparent)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: MarcosJVPR
          outputs: |
            dist/snake.svg?color_snake=%23BF8A0A&color_dots=%23BF8A0A,%23BF8A0A,%23BF8A0A&color_empty=%2300000000&color_back=%2300000000

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}