name: Generate snake

on:
  schedule:
    - cron: "0 0 * * 1"   # every Monday 00:00 UTC
  workflow_dispatch:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake SVG (one file, visible on both themes)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: MarcosJVPR
          # snake azul, comida azules; celdas blancas; fondo transparente
          outputs: |
            dist/snake.svg?color_snake=%23006CFF&color_dots=%23006CFF,%2300BFFF,%2300E5FF&color_empty=%23ffffff&color_back=%2300000000

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
